# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Monash Links
description: A collection of links (and more) for Monash University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://monashlinks.github.io" # the base hostname & protocol for your site
exclude: ['README.md', 'CONTRIBUTING.md', 'Gemfile.lock', 'Gemfile']

# link-directory theme config
remote_theme: epetousis/link-directory
real_name: Monash University
real_home: "https://www.monash.edu/"
source_url: "https://github.com/monashlinks/monashlinks.github.io"
