# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: University of Melbourne Links
description: A collection of links (and more) for The University of Melbourne.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unimelblinks.github.io" # the base hostname & protocol for your site
exclude: ['README.md', 'CONTRIBUTING.md', 'Gemfile.lock', 'Gemfile']

# link-directory theme config
remote_theme: evilgoldfish/link-directory
real_name: The University of Melbourne
real_home: "https://unimelb.edu.au"
source_url: "https://github.com/unimelblinks/unimelblinks.github.io"
